name: Python checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: pip install -r requirements-dev.txt
    - name: Lint
      run: ./lint.sh
    - name: Test
      run: ./test.sh
